name: Build Typescript CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

env:
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install packages
        run: npm install

      - name: Build project
        run: npm run build
