name: Offchain Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Copy env
        run: cp ./contracts/.env.example ./contracts/.env

      - name: Run E2E tests
        run: npm test
        env:
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }} --experimental-vm-modules
